### ISSUE TITLE
PixelCNN at test time

### ISSUE THREAD

**Issue by kolesman** [openai/pixel-cnn#1]
Hi,

I have an issue with model performance at test time. When running the provided code I get the following log:
```
Iteration 0, time = 2875s, train bits_per_dim = 4.3207, test bits_per_dim = 9.4122
Iteration 1, time = 2832s, train bits_per_dim = 3.8210, test bits_per_dim = 9.4122
Iteration 2, time = 2833s, train bits_per_dim = 3.6672, test bits_per_dim = 9.4122
```

My guess is that you have accidentally removed the call of "maintain_averages_op" inside the training cycle. As code search suggests this op is never used:
https://github.com/openai/pixel-cnn/search?utf8=%E2%9C%93&q=maintain_averages_op

**Comment by taesung89** [comment]
+1, I am having the same issue.
