### ISSUE TITLE
How to understand the softmax sampling

### ISSUE THREAD

**Issue by weixsong** [openai/pixel-cnn#24]
Hi,

In the code, logistic distribution sampling is done by:
```python
    # sample mixture indicator from softmax
    sel = tf.one_hot(tf.argmax(logit_probs - tf.log(-tf.log(tf.random_uniform(
        logit_probs.get_shape(), minval=1e-5, maxval=1. - 1e-5))), 3), depth=nr_mix, dtype=tf.float32)
```

I could not understand how it it done this way.

Do I need to compute the CDF of pdf, and then for cdf, minus a random unifrom number, and take log option?

Why here minus a random uniform number make sense?

**Comment by xmasotto** [comment]
This is the Gumbel-max trick, used to efficiently sample from a softmax distribution:
https://hips.seas.harvard.edu/blog/2013/04/06/the-gumbel-max-trick-for-discrete-distributions/

**Comment by weixsong** [comment]
@xmasotto , thanks very much. I got it.
