### ISSUE TITLE
Gated unit formulation

### ISSUE THREAD

**Issue by ngimel** [openai/pixel-cnn#30]
Original PixelCNN paper (https://arxiv.org/pdf/1606.05328.pdf) uses gated unit defined as tanh(a) * sigmoid(b). Same formulation of gated unit is used in the wavenet paper. Yet here you switched to gated unit defined as a*sigmoid(b) https://github.com/openai/pixel-cnn/blob/master/pixel_cnn_pp/nn.py#L286-L287. Is there a reason for this? Does it train better with this nonlinearity?

**Comment by mcdavid109** [comment]
You can view Dauphin et al 2017 work that described Gated Linear Unit
